---
title: "E coli Models"
author: "RJ"
date: "`r Sys.Date()`"
output: html_document
---

Harpeth Conservancy's E. coli models are built using weather and river flow data to predict E. coli levels at each of our sampling locations:



```{r packages, include=FALSE}

library(tidyverse)
library(dataRetrieval)
library(rnoaa)
library(sp)
#library(lawn)
library(dplyr)
library(ggmap)
library(ggplot2)
library(zoo)
library(cropgrowdays)
#library(xlsx)

```



```{r discharge data}

site_no<-c("03433500","03433500","03433500","03432350","03433500","03434500","03431700",
           "03431700","03431060","03431060","0343233905")

Location<-c("Natchez Trace", "Moran Rd. Bridge", "Hwy 100 Boat Launch", "Lowhead Dam",  "Coley Davis", "Hwy 70",            
            "Richland Creek","Jackson Blvd",   "Whitsett Park", "Mill Creek Greenway", "Lewisburg Pike")

LocLookup <- data.frame(Location, site_no)

pCode <- c("00060", "00065","00010","00400")
start.date <- "2020-06-24"
end.date <- "2022-10-10"

Daily <- readNWISdv(siteNumbers = site_no,
                     parameterCd = pCode,
                     startDate = start.date,
                     endDate = end.date)

Daily <- renameNWISColumns(Daily)
names(Daily)



```

```{r sampling data, echo=FALSE}

library(readr)
CSSample <- read_csv("CSSample.csv", col_types = cols(Date = col_date(format = "%m/%d/%Y"), 
    Time = col_skip(), `Turbidity (NTUs)` = col_number(), 
    `E. coli Sample (MPN/100 mL)` = col_number()))
View(CSSample)

names(CSSample)
names(CSSample) [3]<-"Turb"
names(CSSample) [4]<-"Ecoli"

```


```{r weather data, echo=FALSE}


library(readr)
Weather <- read_csv("WeatherData.csv", col_types = cols(DATE = col_date(format = "%Y-%m-%d"), 
    AWND = col_number(), PGTM = col_number(), 
    PRCP = col_number(), SNOW = col_number(), 
    SNWD = col_number(), TAVG = col_number(), 
    TMAX = col_number(), TMIN = col_number(), 
    WDF2 = col_number(), WDF5 = col_number(), 
    WSF2 = col_number(), WSF5 = col_number(), 
    WT01 = col_number(), WT02 = col_number(), 
    WT03 = col_number(), WT04 = col_number(), 
    WT05 = col_number(), WT08 = col_number()))
View(Weather)

names(Weather)[3]<-"Date"

#Create additional weather variables


Weather$prev_two_rainfall = NA

Weather1 <- Weather %>% 
  mutate(prev_two_rainfall = as.numeric(prev_two_rainfall)) %>% 
  rename(rainfall = `PRCP`) %>% 
  replace(is.na(.), 0) %>% 
  mutate(prev_two_rainfall = round(rollsumr(rainfall, k = 2, fill = NA),2),
         prev_two_rainfall = lag(prev_two_rainfall)) %>% 
  filter(Date >= min(Weather$Date) & Date <= max(Weather$Date))


Weather1$prev_three_rainfall = NA

Weather1 <- Weather1 %>% 
  mutate(prev_three_rainfall = as.numeric(prev_three_rainfall)) %>% 
  replace(is.na(.), 0) %>% 
  mutate(prev_three_rainfall = round(rollsumr(rainfall, k = 3, fill = NA),2),
         prev_three_rainfall = lag(prev_three_rainfall)) %>% 
  filter(Date >= min(Weather1$Date) & Date <= max(Weather1$Date))


Weather1$prev_five_rainfall = NA

Weather1 <- Weather1 %>% 
  mutate(prev_five_rainfall = as.numeric(prev_five_rainfall)) %>% 
  replace(is.na(.), 0) %>% 
  mutate(prev_five_rainfall = round(rollsumr(rainfall, k = 5, fill = NA),2),
         prev_five_rainfall = lag(prev_five_rainfall)) %>% 
  filter(Date >= min(Weather1$Date) & Date <= max(Weather1$Date))

#Create sine function for DOY

# y(t)=sin(B(x−C))

B = 0.01721420632
C = 81.75
x = day_of_year(Weather1$Date)

x<-sin(B*(x-C))

#x

#plot(Weather$Date,x)

Weather1$sinDOY<-x







#Split Location Data into Individual Data Frames
##### 


s <- split(Daily, Daily$site_no)

Mill_Creek<-s[[1]]

Richland_Creek<-s[[2]]

Lewisburg_Pike<-s[[3]]

Lowhead_Dam<-s[[4]]

Hwy_100<-s[[5]]

Hwy_70<-s[[6]]


l<-split(CSSample, CSSample$Location)

H100<-l[[2]] # Hwy100

H70<-l[[3]] # Hwy70

Jackson<-l[[4]] #Jackson Blvd

LB_Pike<-l[[5]] #Lewisburg Pike

LH_Dam<-l[[6]] #Lowhead Dam

Mill_CreekGW<-l[[7]] #Mill Creek Grnwy

Moran<-l[[8]] #Moran

RCreek<-l[[11]] #Richland Creek

Browns_Creek<-l[[12]] #West Fork Browns Creek

Whites_Creek<-l[[13]] #Whites Creek

Whitsett<-l[[14]] #Whitsett Park

```

Weather data is compiled and additional variables added (i.e. previous two days of precipitation etc.)

```{r merge data, echo=FALSE}
#Hwy100

str(H100)
str(Hwy_100)

total <- merge(Hwy_100,H100,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Hwy100.csv")


#Lewisburg Pike - NEED TO FIX - two discharge gauges at this location

str(LB_Pike)
str(Lewisburg_Pike)

total <- merge(Lewisburg_Pike,LB_Pike,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Lewisburg_Pike.csv")

#Hwy70

str(H70)
str(Hwy_70)

total <- merge(Hwy_70,H70,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Hwy70.csv")

#Moran

str(Moran)
str(Hwy_100)

total <- merge(Hwy_100,Moran,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Moran.csv")

#Mill CreekGW

str(Mill_Creek)
str(Mill_CreekGW)

total <- merge(Mill_Creek,Mill_CreekGW,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"MillCreekGW.csv")

#write.xlsx(x = total, file = "MillCreekGW.xls")




#Mill Whitsett Park

str(Whitsett)
str(Mill_Creek)

total <- merge(Mill_Creek,Whitsett,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Whitsett.csv")




#Jackson Blvd. - Richland Creek

str(Jackson)
str(Richland_Creek)

total <- merge(Richland_Creek,Jackson,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"Jackson.csv")



#McCabe Park - Richland Creek

str(RCreek)
str(Richland_Creek)

total <- merge(Richland_Creek,RCreek,by="Date")

total <- merge(total,Weather1,by="Date") 

total$ID<-NA
total$ID<-c(1:length(total$Date))

total <- total %>% relocate(ID, .before = Date)

total <- total %>% relocate(Ecoli, .after = ID)

write.csv(total,"McCabe.csv")



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
